/*
 * SEMPLO — runtime for 404.html (generated by scripts/build-pages.mjs).
 *
 * The not-found page shares the portfolio pages' header and footer, so it
 * needs the same chrome: language toggle (data-i18n swap), light/dark switch,
 * the compact-nav burger and the tel:/mailto: links. It must stay light and
 * standalone, so it imports ONLY chrome.js — never page.js, which statically
 * pulls the motion chunk (GSAP + the reveal choreography, ~140 KB) that a page
 * with nothing to reveal has no use for.
 */
import { initTheme, initBurger, initContactLinks, applyLang, storedLang } from './chrome.js'

const prefersReduced = matchMedia('(prefers-reduced-motion: reduce)').matches
initTheme({ prefersReduced })
initBurger()
initContactLinks()
applyLang(storedLang() || 'bg')
document.body.classList.add('is-ready')
